### ISSUE TITLE
Backport to dev_tools the tooling added to solidus_static_content

### ISSUE THREAD

**Issue by elia** [solidusio-contrib/solidus_dev_support#11]
`solidus_static_content` had a number of recent changes devoted to easing the development experience. We want to bring in anything that's both useful and generic enough to be good for all extensions.

### What to do

Make a list of things that should be ported here, open PRs accordingly.

- [x] junit formatter for better circleci output (#6)
- [x] bin/rails bin/rake bin/setup bin/update bin/console scripts, possibly also bin/server and bin/release (#35, [original PR](https://github.com/solidusio-contrib/solidus_static_content/pull/39/files))
- [ ] standardize the extension structure to use the full extension name as main namespace and bundlers gemspec defaults ([original PR](https://github.com/solidusio-contrib/solidus_static_content/pull/39/files))
- [x] move from selenium to apparition + puma for feature specs ([original PR](https://github.com/solidusio-contrib/solidus_static_content/pull/42/files), #22)
